import Foundation

/// UserDefaults wrapper for app preferences.
///
/// ⚠️ EVERY ACCESSOR CALLS `access` / `withMutation` BY HAND, AND HAS TO.
/// `@Observable` instruments *stored* properties; these are computed properties
/// over UserDefaults, so the macro wires up nothing for them and SwiftUI
/// registers no dependency. Reads never became dependencies and writes never
/// invalidated anything, so a view reading one of these simply did not update:
/// a toggle wrote its value and the surrounding `if` never re-evaluated, a
/// Picker wrote a selection and kept showing the old one. Three separate
/// "the control doesn't work" bugs traced back here — the HTTP Server toggle
/// hiding the API key row, the Privacy Guard section, and the screensaver
/// delay picker — before it was worth fixing the cause rather than the symptoms.
///
/// `access` and `withMutation` are generated by the macro and are exactly what
/// it emits for stored properties; calling them explicitly gives a computed
/// property the same observation behaviour.
@Observable
final class Preferences: @unchecked Sendable {
    @MainActor static let shared = Preferences()

    private let defaults = UserDefaults.standard

    // MARK: - Node

    var nodeName: String {
        get {
            access(keyPath: \.nodeName)
            return defaults.string(forKey: "node_name") ?? NodeNameGenerator.generate()
        }
        set {
            withMutation(keyPath: \.nodeName) { defaults.set(newValue, forKey: "node_name") }
        }
    }

    var apiPort: Int {
        get {
            access(keyPath: \.apiPort)
            return defaults.integer(forKey: "api_port").nonZero ?? 8420
        }
        set {
            withMutation(keyPath: \.apiPort) { defaults.set(newValue, forKey: "api_port") }
        }
    }

    var quicPort: Int {
        get {
            access(keyPath: \.quicPort)
            return defaults.integer(forKey: "quic_port").nonZero ?? 8421
        }
        set {
            withMutation(keyPath: \.quicPort) { defaults.set(newValue, forKey: "quic_port") }
        }
    }

    // MARK: - Network

    var networkMode: NetworkMode {
        get {
            access(keyPath: \.networkMode)
            return NetworkMode(rawValue: defaults.string(forKey: "network_mode") ?? "public") ?? .public
        }
        set {
            withMutation(keyPath: \.networkMode) { defaults.set(newValue.rawValue, forKey: "network_mode") }
        }
    }

    var lastLoadedModel: String? {
        get {
            access(keyPath: \.lastLoadedModel)
            return defaults.string(forKey: "last_loaded_model")
        }
        set {
            withMutation(keyPath: \.lastLoadedModel) { defaults.set(newValue, forKey: "last_loaded_model") }
        }
    }

    var hasCompletedOnboarding: Bool {
        get {
            access(keyPath: \.hasCompletedOnboarding)
            return defaults.bool(forKey: "has_completed_onboarding")
        }
        set {
            withMutation(keyPath: \.hasCompletedOnboarding) { defaults.set(newValue, forKey: "has_completed_onboarding") }
        }
    }

    var bootstrapHost: String {
        get {
            access(keyPath: \.bootstrapHost)
            return defaults.string(forKey: "bootstrap_host") ?? BootstrapClient.defaultBootstrap
        }
        set {
            withMutation(keyPath: \.bootstrapHost) { defaults.set(newValue, forKey: "bootstrap_host") }
        }
    }

    var fleetAdminKey: String? {
        get {
            access(keyPath: \.fleetAdminKey)
            return defaults.string(forKey: "fleet_admin_key")
        }
        set {
            withMutation(keyPath: \.fleetAdminKey) { defaults.set(newValue, forKey: "fleet_admin_key") }
        }
    }

    // MARK: - API

    var httpServerEnabled: Bool {
        get {
            access(keyPath: \.httpServerEnabled)
            return defaults.bool(forKey: "http_server_enabled")
        }
        set {
            withMutation(keyPath: \.httpServerEnabled) { defaults.set(newValue, forKey: "http_server_enabled") }
        }
    }

    var apiKey: String {
        get {
            access(keyPath: \.apiKey)
            return defaults.string(forKey: "api_key") ?? ""
        }
        set {
            withMutation(keyPath: \.apiKey) { defaults.set(newValue, forKey: "api_key") }
        }
    }

    /// A fresh management key.
    ///
    /// 160 bits from the system CSPRNG, hex-encoded — long enough that the
    /// per-IP lockout in `NodeAuth` is defence in depth rather than the only
    /// thing standing between a LAN guest and this node's model management.
    /// Prefixed so it is recognisable in a config file or a log line.
    static func generateAPIKey() -> String {
        var bytes = [UInt8](repeating: 0, count: 20)
        if SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes) != errSecSuccess {
            // SecRandom failing is not a reason to hand back something
            // guessable; UUIDs are also CSPRNG-backed on Apple platforms.
            return "mck_" + (UUID().uuidString + UUID().uuidString)
                .replacingOccurrences(of: "-", with: "").lowercased().prefix(40)
        }
        return "mck_" + bytes.map { String(format: "%02x", $0) }.joined()
    }

    /// Mint a management key on first launch if there isn't one.
    ///
    /// ⚠️ A DELIBERATE DIVERGENCE FROM THE PYTHON NODE, WHICH DOES NOT DO THIS.
    /// There, `api_key` defaults to empty and the operator sets
    /// `MYCELLM_API_KEY`; a keyless daemon is still fully manageable over
    /// loopback by someone with a shell on the box. iOS has no env, no config
    /// file and no shell, so "loopback only" is not a stricter default there —
    /// it means the management surface can never be reached by anything, which
    /// is exactly the state every build from 1.1.0 shipped in.
    ///
    /// Generating one is not a weaker posture. The gate is possession of the
    /// key: without one the surface is closed to the LAN, with one it is closed
    /// to everyone who hasn't got 160 unguessable bits. That is a lock fitted
    /// rather than a door welded shut.
    ///
    /// ⚠️ THE FLEET KEY IS POINTEDLY NOT AUTO-GENERATED. It is a shared secret
    /// that enrols this device in remote management by whoever administers a
    /// network — a trust decision the owner has to make, not one to make for
    /// them. Device-local root: generated. Cross-node authority: opt-in.
    @discardableResult
    func ensureAPIKey() -> String {
        let existing = apiKey
        guard existing.isEmpty else { return existing }
        let fresh = Self.generateAPIKey()
        apiKey = fresh
        return fresh
    }

    /// Key for chat↔iCloud sync. Lives here so `AppDatabase` can read it from a
    /// non-isolated context at container-creation time.
    static let chatSyncKey = "chat_sync_icloud"

    /// Sync chat history to the user's private iCloud database.
    ///
    /// ⚠️ OFF BY DEFAULT, DELIBERATELY. Turning this on for existing users on
    /// update would upload every conversation they have ever had to iCloud
    /// without asking — in an app that ships a Privacy Guard specifically
    /// because chats carry credentials and PII. Opting in is the user's call.
    ///
    /// ⚠️ TAKES EFFECT AT NEXT LAUNCH, NOT IMMEDIATELY. SwiftData fixes
    /// `cloudKitDatabase` per configuration at creation, so applying a change
    /// means rebuilding the container — and rebuilding it live meant tearing
    /// the whole view tree down and back up, which threw the user out of
    /// Settings and flashed the splash screen for a checkbox. Deferring costs a
    /// relaunch and is honest about it; `AppDatabase.activeSyncSetting` lets the
    /// UI say so rather than leaving the toggle looking broken.
    var chatSyncEnabled: Bool {
        get {
            access(keyPath: \.chatSyncEnabled)
            return defaults.bool(forKey: Self.chatSyncKey)
        }
        set {
            withMutation(keyPath: \.chatSyncEnabled) {
                defaults.set(newValue, forKey: Self.chatSyncKey)
            }
        }
    }

    /// Allow multi-gigabyte model downloads over cellular / Low Data Mode.
    /// Off by default — see `DownloadPolicy` for why this needed a policy
    /// rather than a confirmation dialog.
    var allowExpensiveDownloads: Bool {
        get {
            access(keyPath: \.allowExpensiveDownloads)
            return defaults.bool(forKey: DownloadPolicy.allowExpensiveKey)
        }
        set {
            withMutation(keyPath: \.allowExpensiveDownloads) { defaults.set(newValue, forKey: DownloadPolicy.allowExpensiveKey) }
        }
    }

    // MARK: - Remote Endpoint

    var remoteEndpoint: String {
        get {
            access(keyPath: \.remoteEndpoint)
            return defaults.string(forKey: "remote_endpoint") ?? NetworkConfig.publicGateway
        }
        set {
            withMutation(keyPath: \.remoteEndpoint) { defaults.set(newValue, forKey: "remote_endpoint") }
        }
    }

    var remoteApiKey: String {
        get {
            access(keyPath: \.remoteApiKey)
            return defaults.string(forKey: "remote_api_key") ?? ""
        }
        set {
            withMutation(keyPath: \.remoteApiKey) { defaults.set(newValue, forKey: "remote_api_key") }
        }
    }

    var remoteModel: String {
        get {
            access(keyPath: \.remoteModel)
            return defaults.string(forKey: "remote_model") ?? ""
        }
        set {
            withMutation(keyPath: \.remoteModel) { defaults.set(newValue, forKey: "remote_model") }
        }
    }

    // MARK: - Privacy Guard

    var sensitiveGuardEnabled: Bool {
        get {
            access(keyPath: \.sensitiveGuardEnabled)
            return defaults.object(forKey: "sensitive_guard_enabled") as? Bool ?? true
        }
        set {
            withMutation(keyPath: \.sensitiveGuardEnabled) { defaults.set(newValue, forKey: "sensitive_guard_enabled") }
        }
    }

    // MARK: - Reasoning ("thinking")

    /// When true, requests to /v1/chat/completions with no explicit `reasoning`
    /// block strip <think>...</think> from responses and ask Qwen3-family
    /// templates to suppress thinking. End-user chat feels clean by default;
    /// power users can opt in to seeing reasoning via the chat UI toggle.
    var hideReasoningByDefault: Bool {
        get {
            access(keyPath: \.hideReasoningByDefault)
            return defaults.object(forKey: "hide_reasoning_by_default") as? Bool ?? true
        }
        set {
            withMutation(keyPath: \.hideReasoningByDefault) { defaults.set(newValue, forKey: "hide_reasoning_by_default") }
        }
    }

    /// Per-chat UI toggle: when true, ChatView shows reasoning in a
    /// collapsible disclosure panel above the answer. Doesn't change
    /// server policy — sends `reasoning: {"exclude": false}` in the
    /// request body so the server emits reasoning_content.
    var chatShowReasoning: Bool {
        get {
            access(keyPath: \.chatShowReasoning)
            return defaults.bool(forKey: "chat_show_reasoning")
        }
        set {
            withMutation(keyPath: \.chatShowReasoning) { defaults.set(newValue, forKey: "chat_show_reasoning") }
        }
    }

    // MARK: - Inference

    /// Default context window for loaded models. Explicit ctx_len on
    /// load requests still wins.
    ///
    /// Unlike Python's MYCELLM_DEFAULT_CTX_LEN=32768, iOS defaults scale
    /// with device physical memory. llama.cpp / MLX allocate KV-cache
    /// AND activation buffers sized by n_ctx, so a 32K context can OOM
    /// Metal on an 8 GB phone even before any tokens are generated.
    /// Recommended tier (matches Apple's per-device memory caps with
    /// the increased-memory-limit entitlement):
    ///
    ///   tier         RAM          default ctx
    ///   ─────────────────────────────────────
    ///   phone-base    6-8 GB      4096
    ///   phone-pro    12 GB        8192
    ///   tablet-pro   16+ GB      16384
    ///
    /// Users can override via the Settings UI or per-load HTTP body.
    var defaultCtxLen: Int {
        get {
            if let n = defaults.object(forKey: "default_ctx_len") as? Int, n > 0 {
                return n
            }
            let gb = HardwareInfo.totalMemoryGB
            if gb >= 14 { return 16384 }
            if gb >= 10 { return 8192 }
            return 4096
        }
        set { defaults.set(newValue, forKey: "default_ctx_len") }
    }

    /// Bounded (rotating) KV cache size in tokens for MLX generation.
    /// 0 (default) = unbounded — KV grows with the context. On jetsam-tight
    /// devices a bound (e.g. 4096) caps per-request KV memory: older entries
    /// are overwritten, trading long-context recall for headroom. Mirrors the
    /// Python node's per-model max_kv_size.
    var maxKVSize: Int {
        get {
            access(keyPath: \.maxKVSize)
            return defaults.object(forKey: "max_kv_size") as? Int ?? 0
        }
        set {
            withMutation(keyPath: \.maxKVSize) { defaults.set(newValue, forKey: "max_kv_size") }
        }
    }

    /// Nonisolated read of maxKVSize for inference actors — `shared` is
    /// MainActor-bound but UserDefaults itself is thread-safe.
    nonisolated static var maxKVSizeValue: Int {
        UserDefaults.standard.object(forKey: "max_kv_size") as? Int ?? 0
    }

    /// When true (default), a model you load in the app is shared on the public
    /// network (scope "public") so this node seeds inference for the public
    /// chat. When false it stays private to this device (scope "home"). The
    /// app's whole premise is contributing compute, so this is opt-out rather
    /// than opt-in — users can turn it off in Settings.
    var shareModelsPublicly: Bool {
        get {
            access(keyPath: \.shareModelsPublicly)
            return defaults.object(forKey: "share_models_publicly") as? Bool ?? true
        }
        set {
            withMutation(keyPath: \.shareModelsPublicly) { defaults.set(newValue, forKey: "share_models_publicly") }
        }
    }

    // MARK: - Credits (cached from the tracker / source of truth)

    /// Last authoritative aggregate balance reconciled from the tracker, cached
    /// so it survives app restart and shows offline (instead of resetting to
    /// the in-memory seed).
    var cachedCreditBalance: Double {
        get {
            access(keyPath: \.cachedCreditBalance)
            return defaults.object(forKey: "cached_credit_balance") as? Double ?? 100.0
        }
        set {
            withMutation(keyPath: \.cachedCreditBalance) { defaults.set(newValue, forKey: "cached_credit_balance") }
        }
    }

    /// Cached per-network authoritative balances (JSON-encoded [NetworkBalance]).
    var cachedNetworkBalancesData: Data? {
        get {
            access(keyPath: \.cachedNetworkBalancesData)
            return defaults.data(forKey: "cached_network_balances")
        }
        set {
            withMutation(keyPath: \.cachedNetworkBalancesData) { defaults.set(newValue, forKey: "cached_network_balances") }
        }
    }

    /// Last authoritative served-inference count from the tracker, cached so the
    /// inference total survives restart (like the balance).
    var cachedServedCount: Int {
        get {
            access(keyPath: \.cachedServedCount)
            return defaults.integer(forKey: "cached_served_count")
        }
        set {
            withMutation(keyPath: \.cachedServedCount) { defaults.set(newValue, forKey: "cached_served_count") }
        }
    }

    // MARK: - Display

    var keepAwake: Bool {
        get {
            access(keyPath: \.keepAwake)
            return defaults.bool(forKey: "keep_awake")
        }
        set {
            withMutation(keyPath: \.keepAwake) { defaults.set(newValue, forKey: "keep_awake") }
        }
    }

    var screenSaverEnabled: Bool {
        get {
            access(keyPath: \.screenSaverEnabled)
            return defaults.bool(forKey: "screen_saver_enabled")
        }
        set {
            withMutation(keyPath: \.screenSaverEnabled) { defaults.set(newValue, forKey: "screen_saver_enabled") }
        }
    }

    /// Minutes of idle before screensaver activates (0 = immediate with keep awake)
    var screenSaverDelay: Int {
        get {
            access(keyPath: \.screenSaverDelay)
            return defaults.integer(forKey: "screen_saver_delay").nonZero ?? 5
        }
        set {
            withMutation(keyPath: \.screenSaverDelay) { defaults.set(newValue, forKey: "screen_saver_delay") }
        }
    }

    var screenSaverShowLogo: Bool {
        get {
            access(keyPath: \.screenSaverShowLogo)
            return defaults.object(forKey: "screen_saver_show_logo") as? Bool ?? true
        }
        set {
            withMutation(keyPath: \.screenSaverShowLogo) { defaults.set(newValue, forKey: "screen_saver_show_logo") }
        }
    }

    var screenSaverShowHostInfo: Bool {
        get {
            access(keyPath: \.screenSaverShowHostInfo)
            return defaults.bool(forKey: "screen_saver_show_host_info")
        }
        set {
            withMutation(keyPath: \.screenSaverShowHostInfo) { defaults.set(newValue, forKey: "screen_saver_show_host_info") }
        }
    }

    var screenSaverShowTime: Bool {
        get {
            access(keyPath: \.screenSaverShowTime)
            return defaults.bool(forKey: "screen_saver_show_time")
        }
        set {
            withMutation(keyPath: \.screenSaverShowTime) { defaults.set(newValue, forKey: "screen_saver_show_time") }
        }
    }

    var screenSaverShowStats: Bool {
        get {
            access(keyPath: \.screenSaverShowStats)
            return defaults.bool(forKey: "screen_saver_show_stats")
        }
        set {
            withMutation(keyPath: \.screenSaverShowStats) { defaults.set(newValue, forKey: "screen_saver_show_stats") }
        }
    }

    // MARK: - Chat State

    var chatRoute: String {
        get {
            access(keyPath: \.chatRoute)
            return defaults.string(forKey: "chat_route") ?? "Network"
        }
        set {
            withMutation(keyPath: \.chatRoute) { defaults.set(newValue, forKey: "chat_route") }
        }
    }

    var lastSessionId: String? {
        get {
            access(keyPath: \.lastSessionId)
            return defaults.string(forKey: "last_session_id")
        }
        set {
            withMutation(keyPath: \.lastSessionId) { defaults.set(newValue, forKey: "last_session_id") }
        }
    }

    // MARK: - Telemetry

    var telemetryEnabled: Bool {
        get {
            access(keyPath: \.telemetryEnabled)
            return defaults.bool(forKey: "telemetry_enabled")
        }
        set {
            withMutation(keyPath: \.telemetryEnabled) { defaults.set(newValue, forKey: "telemetry_enabled") }
        }
    }
}

private extension Int {
    var nonZero: Int? { self == 0 ? nil : self }
}
